		<?php $nothing_msg = 'None right now.'; ?>
<?php //var_dump($user_data); ?>
		<?php if($user_meta['lg_generated'][0]==1){ ?>
		<h3 class="blue-box">DIRECTORY PAGE GENERATED BY LESSER GOOD.</h3>
		<?php }else{ ?>
		
		<?php } ?>
		<?php 		
		$loggedin_user = wp_get_current_user();
		$loggedin_user_causes = get_user_meta(get_current_user_id(),'causes',true);
		$cause_avatar = $user_meta['upme_user_pic_thumb'][0] ? $user_meta['upme_user_pic_thumb'][0] : 'http://1.gravatar.com/avatar/72c354ec39b352bd9cb7d07d7bc324e7?&d=mm&r=g'; 
		?>
		<div id="primary" class="content-area">
		  	<div class="clear"></div>
			<div id="content" class="site-content" role="main">
			<div class="cause-container">
				<div class="cause-content">
			  		<div class="cause-avatar left"><img src="<?php echo $cause_avatar; ?>" /></div>
					<div class="cause-info left">
						<h2 class="cause-name"><?php echo $user_meta['first_name'][0].' '.$user_meta['last_name'][0] ?></h2>
						<div class="cause-org-name"><?php echo $user_meta['org_name'][0] ?></div>
						<div class="cause-name"><?php echo $user_meta['service_location'][0] ?></div>
					</div>
					<div class="cause-contact left">
					  <?php //var_dump($user_meta); ?>
					  <?php if($user_meta['website'][0]){ ?>
						<div class="cause-email"><i class="fa fa-fw fa-globe"></i>&nbsp;<a href="<?php echo $user_meta['website'][0] ?>">Website</a></div>
					  <?php } ?>
					  <?php if($user_meta['user_email'][0]){ ?>
						<div class="cause-email"><i class="fa fa-fw fa-envelope"></i>&nbsp;<a href="mailto: <?php echo $user_meta['user_email'][0] ?>">Email</a></div>
					  <?php } ?>
					  <?php if($user_meta['twitter'][0]){ ?>
						<div class="cause-social"><i class="fa fa-fw fa-twitter"></i>&nbsp;<a href="https://twitter.com/<?php echo $user_meta['twitter'][0] ?>">Twitter</a></div>
					  <?php } ?>
					  <?php if($user_meta['facebook'][0]){ ?>
						<div class="cause-social"><i class="fa fa-fw fa-facebook"></i>&nbsp;<a href="<?php echo $user_meta['facebook'][0] ?>">Facebook</a></div>
					  <?php } ?>
					  <?php if($user_meta['instagram'][0]){ ?>
						<div class="cause-social"><i class="fa fa-fw fa-instagram"></i>&nbsp;<a href="<?php echo $user_meta['instagram'][0] ?>">Instagram</a></div>
					  <?php } ?>
					</div>
				  <div class="follow-button right">
			<?php
				if($user_data->data->ID != get_current_user_id()){
				  //echo $loggedin_user_causes;
				  //echo $user_data->data->ID;
				  // echo strpos($loggedin_user_causes,$user_data->data->ID);
				  
					if (strpos($loggedin_user_causes,$user_data->data->ID)==false) { ?>
						  <button class="btn btn-blue" id="follow-cause" data-authorid="<?php echo $user_data->data->ID; ?>" data-userid="<?php echo get_current_user_id(); ?>" data-field="causes"><i class="fa fa-fw fa-plus"></i>Follow</button>
					<?php }else{ ?>
						  <button class="btn btn-navy" id="follow-cause" data-authorid="<?php echo $user_data->data->ID; ?>" data-userid="<?php echo get_current_user_id(); ?>" data-field="causes"><i class="fa fa-fw fa-times"></i>Unfollow</button>
					<?php } ?>
				<?php } ?>	
				  </div>
					<div class="clear"></div>
				  	<?php if($user_meta['bio'][0]){ ?>
						<div class="cause-bio"><?php echo $user_meta['bio'][0] ?></div>
				  	<?php } ?>
				
					<?php if($user_meta['lg_generated'][0]==1){ ?>
					  <!--Online Donation-->
					  <?php 
						if($user_meta['donation_instructions'][0]){
								echo '<h3>Financial Support</h3>';
								echo $user_meta['donation_instructions'][0];
									 if($user_meta['donation_url'][0]){
									   echo '<br /><a href="'.$user_meta['donation_url'][0].'"><i class="fa fa-fw fa-external-link"></i>Donate Online</a>'; 
									} 
						} 
					  ?>  
					  <!--/Online Donation-->
				  <!--Paypal Integration-->
						<?php
						$paypal_email = $user_meta['paypal_email'][0] ? $user_meta['paypal_email'][0] : 'noemail';
						$fullname = $user_meta['first_name'][0].' '.$user_meta['last_name'][0];
						if($paypal_email!=='noemail'){
						?>
						<!--
				  		<h3>Paypal Donation</h3>
						Donate directly to this cause. One-time or monthly.
						-->
				  		<div class="left halfwidth">
				  		<?php echo do_shortcode('[lg-donate-once email="'.$paypal_email.'" name="One-Time Donation to '.$fullname.'"]'); ?>
				  		</div>
				  		<div class="left halfwidth">
				  		<?php echo do_shortcode('[lg-donate-monthly email="'.$paypal_email.'" name="Monthly Donation to '.$fullname.'"]'); ?>
				  		</div>
				  		<div class="clear"></div>
				  		<?php //echo do_shortcode('[lg-donate-yearly email="'.$paypal_email.'" name="Yearly Donation to '.$fullname.'"]'); ?>
						<!--
						<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
						<input type="hidden" name="cmd" value="_donations">
						<input type="hidden" name="business" value="<?php //echo $paypal_email; ?>">
						<input type="hidden" name="lc" value="US">
						<input type="hidden" name="item_name" value="<?php //echo $fullname ?>">
						<input type="hidden" name="no_note" value="1">
						<input type="hidden" name="no_shipping" value="1">
						<input type="hidden" name="currency_code" value="USD">
						<input type="hidden" name="bn" value="PP-DonationsBF:btn_donate_LG.gif:NonHosted">
						<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
						<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
						</form>
						-->
						<?php } ?>
				<!--/Paypal Integration-->
				  <!--Square Integration-->
				  <?php 
				  	$square_appid = $user_meta['square_appid'][0]; 
				  	if($square_appid){
				  ?>
				  	<h3 class="widget-title">Square Donate</h3>
			  		<?php include(locate_template('square-form.php')); ?>
				  <?php } ?>
				  <!--/Square Integration-->
					<?php } ?>
				  </div>
			</div>
			  <?php if($user_meta['lg_generated'][0]==1){ ?>
			    
			  <?php }else{ ?>
					<div class="cause-content">
					  <?php //get_search_form(); ?>
					  <?php 
						  if(is_author()){
						  	$editmode = 1;
						  }
					  ?>
						<?php include(locate_template('content-loop.php')); ?>
						<?php comments_template( '', true ); ?>
			  		</div>
			  <?php } ?>
			</div><!-- #content .site-content -->
		</div><!-- #primary .content-area -->
  <?php 
//echo $loggedin_user_causes;
  ?>
<?php if($user_meta['lg_generated'][0]==1){ ?>
<div id="secondary">
<!--Cause Link-->
		<div class="cause-link left">
			<div class="direct-link-detail left"><b>Direct Link:</b> share and print on handouts</div>
		  <br /><a class="left" href="http://lsrgd.in/<?php echo $user_data->user_login ?>">lsrgd.in/<?php echo $user_data->user_login ?></a>
		</div>
  <div class="clear"></div>
  <br />
<!--/Cause Link-->
  <div class="widget">
	  	<div class="widget-content">
		  <h3 class="widget-title">About This Cause</h3>
		  This cause (organization) can claim this page, but until they do, we provide their public information to direct support to their cause.
  		</div>
	</div>
  	<div class="widget">
	  	<div class="widget-content">
		  <h3 class="widget-title">Is this your cause?</h3>
		  <?php
 		 	if($user_meta['supporters'][0]){
				$supporter_count = count(explode(',',$user_meta['supporters'][0]));
				if($supporter_count > 1){
					$supporter_label = 'supporters';
				}else{
					$supporter_label = 'supporter';
				}
			  echo 'You have <b>'.$supporter_count.' '.$supporter_label.'</b> waiting to connect with you. Claim your cause now:<br />';
			}else{
			  echo 'No supporters yet. Get ready to connect with supporters and claim your cause now:<br />';
			}
		  ?>
		  <br />
		  <button class="btn btn-blue" onclick="window.location.href='/claim'"><i class="fa fa-fw fa-check"></i>Claim This Cause</button>
  		</div>
	</div>
</div>
<?php }else{ ?>
<!--CAUSE OWNED PROFILE-->
<!--SIDEBAR-->
<?php //var_dump($user_data); ?>
<div id="secondary">
<!--Cause Link-->
		<div class="cause-link left">
			<div class="direct-link-detail"><b>Direct Link:</b> share and print on handouts</div>
		  
		  	<a class="left" href="http://lsrgd.in/<?php echo $user_data->user_login ?>">lsrgd.in/<?php echo $user_data->user_login ?></a>
		</div>
  <div class="clear"></div>
  <br />
		<!--/Cause Link-->
  <!--Ongoing Prayer Needs-->
  <div class="widget">
	  	<div class="widget-content">
  			<h3 class="widget-title">Prayer</h3>
  			<?php echo $user_meta['static_needs_prayer'][0] ? $user_meta['static_needs_prayer'][0] : $nothing_msg; ?>
		</div>
  </div>
  <!--/Ongoing Prayer Needs-->
  <!--Ongoing Financial Needs-->
  <div class="widget">
	  	<div class="widget-content">
		  	<h3 class="widget-title">Financial Support</h3>
  			<?php
 		 	if(!$user_meta['donation_instructions'][0]){
				echo $user_meta['static_needs_financial'][0] ? $user_meta['static_needs_financial'][0] : $nothing_msg; 
			}
		  	?>
		</div>
  </div>
  <!--/Ongoing Financial Needs-->
  <!--Online Donation-->
  <?php 
  	if($user_meta['donation_instructions'][0]){
		echo '<div class="widget">';
		  echo '<div class="widget-content">';  
	  		echo '<div>'.$user_meta['donation_instructions'][0].'</div>';
	  		
			 	 if($user_meta['donation_url'][0]){
				   echo '<br /><a href="'.$user_meta['donation_url'][0].'"><i class="fa fa-fw fa-external-link"></i>Donate Online</a>'; 
				} 
	  	  	echo '</div>';
	  echo '</div>';
	} 
  ?>  
  <!--/Online Donation-->
  <!--Paypal Integration-->
    <div class="widget">
	  	<div class="widget-content">
		  <?php
		  $paypal_email = $user_meta['paypal_email'][0] ? $user_meta['paypal_email'][0] : 'noemail';
		  $fullname = $user_meta['first_name'][0].' '.$user_meta['last_name'][0];
		  if($paypal_email!=='noemail'){
		  ?>
		  
		  <div class="left fullwidth">
		  	<?php echo do_shortcode('[lg-donate-once email="'.$paypal_email.'" name="One-Time Donation to '.$fullname.'"]'); ?>
		  </div>
		  <div class="left fullwidth">
		  	<?php echo do_shortcode('[lg-donate-monthly email="'.$paypal_email.'" name="Monthly Donation to '.$fullname.'"]'); ?>
		  </div>
		  <div class="clear"></div>
		  <!--
		  <h3 class="widget-title">Paypal Donation</h3>
		  Donate directly to this cause. One-time or monthly, a PayPal account not required.
		  <br /><br />
		  <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
		  <input type="hidden" name="cmd" value="_donations">
		  <input type="hidden" name="business" value="<?php echo $paypal_email; ?>">
		  <input type="hidden" name="lc" value="US">
		  <input type="hidden" name="item_name" value="<?php echo $fullname ?>">
		  <input type="hidden" name="no_note" value="1">
		  <input type="hidden" name="no_shipping" value="1">
		  <input type="hidden" name="currency_code" value="USD">
		  <input type="hidden" name="bn" value="PP-DonationsBF:btn_donate_LG.gif:NonHosted">
		  <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
		  <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
		  </form>
		  -->
		  <?php } ?>
	  </div>
  </div>
  <!--/Paypal Integration-->
	<!--Square Integration-->
	<?php 
	  $square_appid = $user_meta['square_appid'][0]; 
	  if($square_appid){
	?>
  	<h3 class="widget-title">Square Donate</h3>
	  <?php include(locate_template('square-form.php')); ?>
	<?php } ?>
	<!--/Square Integration-->
				   
  <!--Ongoing Items Needs-->
    <div class="widget">
	  	<div class="widget-content">
		  	<h3 class="widget-title">Donate Items</h3>
 				<?php echo $user_meta['static_needs_items'][0] ? $user_meta['static_needs_items'][0] : $nothing_msg; ?>
	  	</div>
  	</div>
  <!--/Ongoing Items Needs-->
  <!--Ongoing Volunteer Needs-->
  <div class="widget">
	  	<div class="widget-content">
		  	<h3 class="widget-title">Volunteer</h3>
  				<?php echo $user_meta['static_needs_volunteer'][0] ? $user_meta['static_needs_volunteer'][0] : $nothing_msg; ?>
		</div>
  </div>
  <!--/Ongoing Volunteer Needs-->
</div>
<?php } ?>
  </div>
<!--/SIDEBAR-->